version: '2'
services:
    janus-gateway:
        image: canyan/janus-gateway:latest
        container_name: janus-gateway
        #volumes:
            #- "./etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
            #- "./etc/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
        ports:
            - "8088:8088"
            - "8089:8089"
            - "8889:8889"
            - "8000:8000"
            - "7088:7088"
            - "7089:7089"
    nginx:
        image: "nginx:alpine"
        volumes:
            - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"
        depends_on:
            - "janus-gateway"
        restart: "unless-stopped"
